In [632]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('wrangled.csv')

In [633]:
df.head()

,Unnamed: 0,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail,home_id,away_id
0,0,09/01/1979,1979,1,False,Tampa Bay Buccaneers,31,16,Detroit Lions,TB,-3.0,30,Houlihan's Stadium,False,79.0,9.0,87.0,NaN,TB,DET
1,1,09/02/1979,1979,1,False,Buffalo Bills,7,9,Miami Dolphins,MIA,-5.0,39,Ralph Wilson Stadium,False,74.0,15.0,74.0,NaN,BUF,MIA
2,2,09/02/1979,1979,1,False,Chicago Bears,6,3,Green Bay Packers,CHI,-3.0,31,Soldier Field,False,78.0,11.0,68.0,NaN,CHI,GB
3,3,09/02/1979,1979,1,False,Denver Broncos,10,0,Cincinnati Bengals,DEN,-3.0,31.5,Mile High Stadium,False,69.0,6.0,38.0,NaN,DEN,CIN
4,4,09/02/1979,1979,1,False,Kansas City Chiefs,14,0,Baltimore Colts,KC,-1.0,37,Arrowhead Stadium,False,76.0,8.0,71.0,NaN,KC,IND

In [634]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10177 entries, 0 to 10176
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           10177 non-null  int64
 1   schedule_date        10177 non-null  object
 2   schedule_season      10177 non-null  int64
 3   schedule_week        10177 non-null  object
 4   schedule_playoff     10177 non-null  bool
 5   team_home            10177 non-null  object
 6   score_home           10177 non-null  int64
 7   score_away           10177 non-null  int64
 8   team_away            10177 non-null  object
 9   team_favorite_id     10177 non-null  object
 10  spread_favorite      10177 non-null  float64
 11  over_under_line      10177 non-null  object
 12  stadium              10177 non-null  object
 13  stadium_neutral      10177 non-null  bool
 14  weather_temperature  9665 non-null   float64
 15  weather_wind_mph     9665 non-null   float64
 16  weather_humidity     6278 non-null   float64
 17  weather_detail       2480 non-null   object
 18  home_id              10177 non-null  object
 19  away_id              10177 non-null  object
dtypes: bool(2), float64(4), int64(4), object(10)
memory usage: 1.4+ MB

In [635]:
#double up the data so there is a row for each team in each game.  This seems redundant but the prior
#week info will be different when the home team is in the team position vs opponent position

data1 = [df["schedule_date"], df["schedule_season"], df["schedule_week"], df["schedule_playoff"], df["home_id"],df["score_home"], df["away_id"], df["score_away"], df["team_favorite_id"], df["spread_favorite"], df["over_under_line"]]
data2 = [df["schedule_date"], df["schedule_season"], df["schedule_week"], df["schedule_playoff"], df["away_id"],df["score_away"], df["home_id"], df["score_home"], df["team_favorite_id"], df["spread_favorite"], df["over_under_line"]]



headers = ["date", "season","week","playoff","team_id","team_score","opponent_id","opponent_score","favorite","spread","overunder"]

hometeams = pd.concat(data1, axis=1, keys=headers)
awayteams = pd.concat(data2, axis=1, keys=headers)

hometeams['home'] = 1
awayteams['home'] = 0

In [636]:
awayteams.head()

,date,season,week,playoff,team_id,team_score,opponent_id,opponent_score,favorite,spread,overunder,home
0,09/01/1979,1979,1,False,DET,16,TB,31,TB,-3.0,30,0
1,09/02/1979,1979,1,False,MIA,9,BUF,7,MIA,-5.0,39,0
2,09/02/1979,1979,1,False,GB,3,CHI,6,CHI,-3.0,31,0
3,09/02/1979,1979,1,False,CIN,0,DEN,10,DEN,-3.0,31.5,0
4,09/02/1979,1979,1,False,IND,0,KC,14,KC,-1.0,37,0

In [637]:
df = pd.concat([hometeams,awayteams],ignore_index=True)

In [638]:
df.shape

(20354, 12)

In [639]:
df.head()

,date,season,week,playoff,team_id,team_score,opponent_id,opponent_score,favorite,spread,overunder,home
0,09/01/1979,1979,1,False,TB,31,DET,16,TB,-3.0,30,1
1,09/02/1979,1979,1,False,BUF,7,MIA,9,MIA,-5.0,39,1
2,09/02/1979,1979,1,False,CHI,6,GB,3,CHI,-3.0,31,1
3,09/02/1979,1979,1,False,DEN,10,CIN,0,DEN,-3.0,31.5,1
4,09/02/1979,1979,1,False,KC,14,IND,0,KC,-1.0,37,1

In [640]:
df['week'].unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', 'Wildcard', 'Division', 'Conference',
       'Superbowl', '17', '18', 'WildCard', 'SuperBowl'], dtype=object)

In [641]:
#get rid of playoffs
keeps = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12','13', '14', '15', '16','17','18']

df = df[df.week.isin(keeps)]

In [642]:
df['week'].unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18'], dtype=object)

In [643]:
df['week'] = df['week'].astype(np.int64)

In [644]:
df.sort_values(by=['season','team_id','week'], inplace=True)

In [645]:
#add previous week - bye weeks mean not necessarily week-1
df['prev_week'] = df.week.shift(1)

In [646]:
#add previous date - bye weeks mean not necessarily week-1
df['prev_date'] = df.date.shift(1)

In [647]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19484 entries, 11 to 20331
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            19484 non-null  object
 1   season          19484 non-null  int64
 2   week            19484 non-null  int64
 3   playoff         19484 non-null  bool
 4   team_id         19484 non-null  object
 5   team_score      19484 non-null  int64
 6   opponent_id     19484 non-null  object
 7   opponent_score  19484 non-null  int64
 8   favorite        19484 non-null  object
 9   spread          19484 non-null  float64
 10  overunder       19484 non-null  object
 11  home            19484 non-null  int64
 12  prev_week       19483 non-null  float64
 13  prev_date       19483 non-null  object
dtypes: bool(1), float64(2), int64(5), object(6)
memory usage: 2.1+ MB

In [648]:
import time
df['date'] = pd.to_datetime(df['date'])
df['prev_date'] = pd.to_datetime(df['prev_date'])

In [649]:
#add days since last game
from datetime import datetime
df['days_since'] = (df['date'] - df['prev_date']).dt.days

In [650]:
df.loc[(df['season'] == 1999) & (df['team_id'] == 'DEN')]

,date,season,week,playoff,team_id,team_score,opponent_id,opponent_score,favorite,spread,overunder,home,prev_week,prev_date,days_since
4608,1999-09-13,1999,1,False,DEN,21,MIA,38,DEN,-6.0,43,1,17.0,2000-01-02,-111.0
14792,1999-09-19,1999,2,False,DEN,10,KC,26,DEN,-3.5,40.5,0,1.0,1999-09-13,6.0
14813,1999-09-26,1999,3,False,DEN,10,TB,13,TB,-2.5,38,0,2.0,1999-09-19,7.0
4643,1999-10-03,1999,4,False,DEN,13,NYJ,21,DEN,-5.5,40,1,3.0,1999-09-26,7.0
14838,1999-10-10,1999,5,False,DEN,16,OAK,13,OAK,-7.0,38,0,4.0,1999-10-03,7.0
4671,1999-10-17,1999,6,False,DEN,31,GB,10,GB,-3.5,40,1,5.0,1999-10-10,7.0
14863,1999-10-24,1999,7,False,DEN,23,NE,24,NE,-3.5,40.5,0,6.0,1999-10-17,7.0
4698,1999-10-31,1999,8,False,DEN,20,MIN,23,MIN,-2.5,45,1,7.0,1999-10-24,7.0
14894,1999-11-07,1999,9,False,DEN,33,LAC,17,PICK,0.0,35.5,0,8.0,1999-10-31,7.0
14910,1999-11-14,1999,10,False,DEN,17,SEA,20,SEA,-5.5,41,0,9.0,1999-11-07,7.0
4751,1999-11-22,1999,11,False,DEN,27,OAK,21,DEN,-1.5,37,1,10.0,1999-11-14,8.0
4774,1999-12-05,1999,13,False,DEN,10,KC,16,DEN,-3.5,38.5,1,11.0,1999-11-22,13.0
14973,1999-12-13,1999,14,False,DEN,24,JAX,27,JAX,-9.0,37.5,0,13.0,1999-12-05,8.0
4804,1999-12-19,1999,15,False,DEN,36,SEA,30,DEN,-1.5,39,1,14.0,1999-12-13,6.0
14990,1999-12-25,1999,16,False,DEN,17,DET,7,DET,-4.5,43.5,0,15.0,1999-12-19,6.0
4831,2000-01-02,1999,17,False,DEN,6,LAC,12,DEN,-7.0,37.5,1,16.0,1999-12-25,8.0

In [651]:
#add cumulative point totals
df['points_for'] = df.groupby(['season','team_id'])['team_score'].transform(pd.Series.cumsum)
df['points_against'] = df.groupby(['season','team_id'])['opponent_score'].transform(pd.Series.cumsum)

In [652]:
df.head(450)

,date,season,week,playoff,team_id,team_score,opponent_id,opponent_score,favorite,spread,overunder,home,prev_week,prev_date,days_since,points_for,points_against
11,1979-09-02,1979,1,False,ARI,21,DAL,22,DAL,-4.0,37,1,NaN,NaT,NaN,21,22
10200,1979-09-09,1979,2,False,ARI,27,NYG,14,ARI,-3.0,36,0,1.0,1979-09-02,7.0,48,36
40,1979-09-16,1979,3,False,ARI,21,PIT,24,PIT,-6.0,40,1,2.0,1979-09-09,7.0,69,60
53,1979-09-23,1979,4,False,ARI,7,WAS,17,ARI,-3.0,39,1,3.0,1979-09-16,7.0,76,77
10239,1979-09-30,1979,5,False,ARI,0,LAR,21,LAR,-6.0,38,0,4.0,1979-09-23,7.0,76,98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,1979-12-02,1979,14,False,WAS,38,GB,21,WAS,-9.0,34,1,13.0,1979-11-25,7.0,286,246
208,1979-12-09,1979,15,False,WAS,28,CIN,14,WAS,-6.0,42,1,14.0,1979-12-02,7.0,314,260
10392,1979-12-16,1979,16,False,WAS,34,DAL,35,DAL,-8.0,39.5,0,15.0,1979-12-09,7.0,348,295
245,1980-09-07,1980,1,False,ARI,35,NYG,41,ARI,-7.0,42,1,16.0,1979-12-16,266.0,35,41
10436,1980-09-14,1980,2,False,ARI,21,SF,24,SF,-3.0,42,0,1.0,1980-09-07,7.0,56,65

In [653]:
df['overunder'].unique()

array(['37', '36', '40', '39', '38', '42', '43', '32', '35.5', '35', '45',
       '34', '44', '41', '31', '31.5', '44.5', '39.5', '30', '33', '42.5',
       '36.5', '40.5', '49', '50', '46', '48', '47', '51', '54', '45.5',
       '43.5', '46.5', '52', '52.5', '54.5', '47.5', '38.5', '37.5',
       '34.5', '41.5', '53', '55', '53.5', '48.5', '49.5', '50.5', '51.5',
       '56', '33.5', '28', '32.5', '36.6', '29.5', '58.5', '59.5', '58',
       '55.5', '63', '56.5', '57', '60', '30.5', '57.5', '59', '61.5',
       '63.5'], dtype=object)

In [654]:
df['overunder'] = df['overunder'].astype(np.float)

In [655]:
#add performance against spreads
df['covered_by'] = np.where(df['team_id'] == df['favorite'], df['team_score'] - df['opponent_score'] + df['spread'], df['opponent_score'] - df['team_score'] + df['spread'])
df['covered_over_by'] = ((df['team_score'] + df['opponent_score']) - df['overunder'])

In [656]:
df.prev_week.unique()

array([nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18.])

In [657]:
df.head()

,date,season,week,playoff,team_id,team_score,opponent_id,opponent_score,favorite,spread,overunder,home,prev_week,prev_date,days_since,points_for,points_against,covered_by,covered_over_by
11,1979-09-02,1979,1,False,ARI,21,DAL,22,DAL,-4.0,37.0,1,NaN,NaT,NaN,21,22,-3.0,6.0
10200,1979-09-09,1979,2,False,ARI,27,NYG,14,ARI,-3.0,36.0,0,1.0,1979-09-02,7.0,48,36,10.0,5.0
40,1979-09-16,1979,3,False,ARI,21,PIT,24,PIT,-6.0,40.0,1,2.0,1979-09-09,7.0,69,60,-3.0,5.0
53,1979-09-23,1979,4,False,ARI,7,WAS,17,ARI,-3.0,39.0,1,3.0,1979-09-16,7.0,76,77,-13.0,-15.0
10239,1979-09-30,1979,5,False,ARI,0,LAR,21,LAR,-6.0,38.0,0,4.0,1979-09-23,7.0,76,98,15.0,-17.0

In [658]:
df['covered'] = np.where(df['covered_by'] > 0, 1,0)

In [659]:
df['covered_over'] = np.where(df['covered_over_by'] > 0, 1,0)

In [660]:
df['push'] = np.where(df['covered_by'] == 0, 1,0)

In [661]:
df['push_over'] = np.where(df['covered_over_by'] == 0, 1,0)

In [662]:
df['win_by'] = df['team_score'] - df['opponent_score']

In [663]:
df['win'] = np.where(df['win_by'] > 0, 1,0)

In [664]:
df['loss'] = np.where(df['win_by'] < 0, 1,0)

In [665]:
df['tie'] = np.where(df['win_by'] == 0, 1,0)

In [666]:
df['total_wins'] = df.groupby(['season','team_id'])['win'].transform(pd.Series.cumsum)
df['total_losses'] = df.groupby(['season','team_id'])['loss'].transform(pd.Series.cumsum)
df['win_loss_ratio'] = (df['total_wins'])/np.where(df['total_losses'] == 0, 1,df['total_losses'])
df['pfa_ratio'] = (df['points_for'])/np.where(df['points_against'] == 0, 1,df['points_against'])
df['net_wins'] = df['total_wins']-df['total_losses']
df['net_pfa'] = df['points_for']-df['points_against']
df['net_pfa_avg'] = (df['points_for']-df['points_against'])/df['week']

In [667]:
df['push'].value_counts()

0    18930
1      554
Name: push, dtype: int64

In [668]:
df['favorite'].value_counts()

PIT     850
NE      822
DEN     816
DAL     802
SF      786
GB      746
PHI     732
MIN     712
MIA     680
NO      652
NYG     650
LAC     646
SEA     644
KC      628
WAS     614
LAR     612
OAK     606
CHI     606
TEN     602
BUF     594
ATL     584
IND     580
NYJ     564
CIN     516
TB      476
DET     474
BAL     438
ARI     420
CLE     414
CAR     378
JAX     322
PICK    282
HOU     236
Name: favorite, dtype: int64

In [669]:
#bring previous week results into current week
df.sort_values(by=['season','week','home'], inplace=True)
df = df.merge(df,how='left',suffixes=('', '_p'), left_on=['team_id','season','prev_week'], right_on=['team_id','season','week'])

In [670]:
df.head()

,date,season,week,playoff,team_id,team_score,opponent_id,opponent_score,favorite,spread,overunder,home,prev_week,prev_date,days_since,points_for,points_against,covered_by,covered_over_by,covered,covered_over,push,push_over,win_by,win,loss,tie,total_wins,total_losses,win_loss_ratio,pfa_ratio,net_wins,net_pfa,net_pfa_avg,date_p,week_p,playoff_p,team_score_p,opponent_id_p,opponent_score_p,favorite_p,spread_p,overunder_p,home_p,prev_week_p,prev_date_p,days_since_p,points_for_p,points_against_p,covered_by_p,covered_over_by_p,covered_p,covered_over_p,push_p,push_over_p,win_by_p,win_p,loss_p,tie_p,total_wins_p,total_losses_p,win_loss_ratio_p,pfa_ratio_p,net_wins_p,net_pfa_p,net_pfa_avg_p
0,1979-09-02,1979,1,False,ATL,40,NO,34,NO,-5.0,32.0,0,16.0,1979-12-16,-105.0,40,34,-11.0,42.0,0,1,0,0,6,1,0,0,1,0,1.0,1.176471,1,6,6.0,1979-12-16,16.0,False,31.0,SF,21.0,ATL,-3.0,45.0,1.0,15.0,1979-12-09,7.0,300.0,388.0,7.0,7.0,1.0,1.0,0.0,0.0,10.0,1.0,0.0,0.0,6.0,10.0,0.600000,0.773196,-4.0,-88.0,-5.5000
1,1979-09-02,1979,1,False,CIN,0,DEN,10,DEN,-3.0,31.5,0,16.0,1979-12-16,-105.0,0,10,7.0,-21.5,1,0,0,0,-10,0,1,0,0,1,0.0,0.000000,-1,-10,-10.0,1979-12-16,16.0,False,16.0,CLE,12.0,CIN,-1.0,41.0,1.0,15.0,1979-12-09,7.0,337.0,421.0,3.0,-13.0,1.0,0.0,0.0,0.0,4.0,1.0,0.0,0.0,4.0,12.0,0.333333,0.800475,-8.0,-84.0,-5.2500
2,1979-09-02,1979,1,False,CLE,25,NYJ,22,NYJ,-2.0,41.0,0,16.0,1979-12-16,-105.0,25,22,-5.0,6.0,0,1,0,0,3,1,0,0,1,0,1.0,1.136364,1,3,3.0,1979-12-16,16.0,False,12.0,CIN,16.0,CIN,-1.0,41.0,0.0,15.0,1979-12-09,7.0,359.0,352.0,3.0,-13.0,1.0,0.0,0.0,0.0,-4.0,0.0,1.0,0.0,9.0,7.0,1.285714,1.019886,2.0,7.0,0.4375
3,1979-09-02,1979,1,False,DAL,22,ARI,21,DAL,-4.0,37.0,0,16.0,1979-12-16,-105.0,22,21,-3.0,6.0,0,1,0,0,1,1,0,0,1,0,1.0,1.047619,1,1,1.0,1979-12-16,16.0,False,35.0,WAS,34.0,DAL,-8.0,39.5,1.0,15.0,1979-12-08,8.0,371.0,313.0,-7.0,29.5,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,11.0,5.0,2.200000,1.185304,6.0,58.0,3.6250
4,1979-09-01,1979,1,False,DET,16,TB,31,TB,-3.0,30.0,0,16.0,1979-12-17,-107.0,16,31,12.0,17.0,1,1,0,0,-15,0,1,0,0,1,0.0,0.516129,-1,-15,-15.0,1979-12-15,16.0,False,13.0,GB,18.0,DET,-3.0,34.0,1.0,15.0,1979-12-09,6.0,219.0,365.0,-8.0,-3.0,0.0,0.0,0.0,0.0,-5.0,0.0,1.0,0.0,2.0,14.0,0.142857,0.600000,-12.0,-146.0,-9.1250

In [671]:
#remove zero spread rows
df = df[(df.favorite != "PICK")]
#remove week 1 rows - previous week not valid
df = df[(df.week != 1)]

In [672]:
df_output = df.groupby('home').mean().T
df_output
#confirm averages make sense - home teams score 2.5pts more on average

home                        0           1
season                2000.02     2000.02
week                  9.58858      9.5904
playoff                 False       False
team_score            19.9232     22.6155
opponent_score        22.6226     19.9211
spread               -5.48417    -5.48439
overunder             41.9082     41.9071
prev_week             8.52671     8.52472
days_since            7.46162     7.48661
points_for             188.69     190.348
points_against        190.041     188.828
covered_by          -0.124403   -0.128348
covered_over_by      0.637654    0.629492
covered              0.469732    0.469608
covered_over         0.484394    0.484165
push                0.0281017   0.0281142
push_over           0.0187715   0.0187799
win_by               -2.69932     2.69441
win                  0.419971    0.577731
loss                 0.577807    0.420047
tie                0.00222148  0.00222247
total_wins            4.41431     4.49328
total_losses          4.48484     4.41238
win_loss_ratio        1.49262     1.56629
pfa_ratio             1.05867     1.08664
net_wins            -0.070532   0.0808979
net_pfa              -1.35166     1.51961
net_pfa_avg         -0.207713    0.219578
week_p                8.52671     8.52472
team_score_p          21.8157     20.6483
opponent_score_p      20.7388     21.7183
spread_p             -5.34827    -5.30426
overunder_p           41.9255     41.9114
home_p               0.702544      0.2977
prev_week_p           8.58942     8.58395
days_since_p         0.381471    0.387154
points_for_p          168.885     167.826
points_against_p      167.565     169.032
covered_by_p        -0.389037   0.0240027
covered_over_by_p    0.629001    0.455184
covered_p            0.465178    0.469719
covered_over_p       0.485616    0.477831
push_p              0.0302122   0.0283365
push_over_p         0.0188826   0.0194466
win_by_p              1.07697    -1.07001
win_p                0.531267    0.467052
loss_p               0.465734     0.53117
tie_p                0.002999  0.00177798
total_wins_p          3.99733     3.91732
total_losses_p        3.91103       3.996
win_loss_ratio_p       1.4988     1.42808
pfa_ratio_p           1.15202     1.11825
net_wins_p          0.0863046  -0.0786754
net_pfa_p             1.31978    -1.20547
net_pfa_avg_p        0.260697    -0.25215

In [673]:
df.head(20)

,date,season,week,playoff,team_id,team_score,opponent_id,opponent_score,favorite,spread,overunder,home,prev_week,prev_date,days_since,points_for,points_against,covered_by,covered_over_by,covered,covered_over,push,push_over,win_by,win,loss,tie,total_wins,total_losses,win_loss_ratio,pfa_ratio,net_wins,net_pfa,net_pfa_avg,date_p,week_p,playoff_p,team_score_p,opponent_id_p,opponent_score_p,favorite_p,spread_p,overunder_p,home_p,prev_week_p,prev_date_p,days_since_p,points_for_p,points_against_p,covered_by_p,covered_over_by_p,covered_p,covered_over_p,push_p,push_over_p,win_by_p,win_p,loss_p,tie_p,total_wins_p,total_losses_p,win_loss_ratio_p,pfa_ratio_p,net_wins_p,net_pfa_p,net_pfa_avg_p
28,1979-09-09,1979,2,False,ARI,27,NYG,14,ARI,-3.0,36.0,0,1.0,1979-09-02,7.0,48,36,10.0,5.0,1,1,0,0,13,1,0,0,1,1,1.0,1.333333,0,12,6.0,1979-09-02,1.0,False,21.0,DAL,22.0,DAL,-4.0,37.0,1.0,NaN,NaT,NaN,21.0,22.0,-3.0,6.0,0.0,1.0,0.0,0.0,-1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.954545,-1.0,-1.0,-1.0
29,1979-09-10,1979,2,False,ATL,14,PHI,10,PHI,-4.0,35.5,0,1.0,1979-09-02,8.0,54,44,-8.0,-11.5,0,0,0,0,4,1,0,0,2,0,2.0,1.227273,2,10,5.0,1979-09-02,1.0,False,40.0,NO,34.0,NO,-5.0,32.0,0.0,16.0,1979-12-16,-105.0,40.0,34.0,-11.0,42.0,0.0,1.0,0.0,0.0,6.0,1.0,0.0,0.0,1.0,0.0,1.0,1.176471,1.0,6.0,6.0
30,1979-09-09,1979,2,False,CIN,24,BUF,51,CIN,-3.0,34.0,0,1.0,1979-09-02,7.0,24,61,-30.0,41.0,0,1,0,0,-27,0,1,0,0,2,0.0,0.393443,-2,-37,-18.5,1979-09-02,1.0,False,0.0,DEN,10.0,DEN,-3.0,31.5,0.0,16.0,1979-12-16,-105.0,0.0,10.0,7.0,-21.5,1.0,0.0,0.0,0.0,-10.0,0.0,1.0,0.0,0.0,1.0,0.0,0.000000,-1.0,-10.0,-10.0
32,1979-09-09,1979,2,False,DAL,21,SF,13,DAL,-13.0,39.0,0,1.0,1979-09-02,7.0,43,34,-5.0,-5.0,0,0,0,0,8,1,0,0,2,0,2.0,1.264706,2,9,4.5,1979-09-02,1.0,False,22.0,ARI,21.0,DAL,-4.0,37.0,0.0,16.0,1979-12-16,-105.0,22.0,21.0,-3.0,6.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.047619,1.0,1.0,1.0
33,1979-09-06,1979,2,False,LAR,13,DEN,9,DEN,-2.0,31.5,0,1.0,1979-09-02,4.0,30,33,-6.0,-9.5,0,0,0,0,4,1,0,0,1,1,1.0,0.909091,0,-3,-1.5,1979-09-02,1.0,False,17.0,OAK,24.0,LAR,-4.0,36.5,1.0,16.0,1979-12-17,-106.0,17.0,24.0,-11.0,4.5,0.0,1.0,0.0,0.0,-7.0,0.0,1.0,0.0,0.0,1.0,0.0,0.708333,-1.0,-7.0,-7.0
34,1979-09-09,1979,2,False,MIN,7,CHI,26,CHI,-6.0,31.5,0,1.0,1979-09-02,7.0,35,48,13.0,1.5,1,1,0,0,-19,0,1,0,1,1,1.0,0.729167,0,-13,-6.5,1979-09-02,1.0,False,28.0,SF,22.0,MIN,-7.0,32.0,1.0,16.0,1979-12-15,-104.0,28.0,22.0,-1.0,18.0,0.0,1.0,0.0,0.0,6.0,1.0,0.0,0.0,1.0,0.0,1.0,1.272727,1.0,6.0,6.0
35,1979-09-09,1979,2,False,NO,19,GB,28,GB,-3.0,35.0,0,1.0,1979-09-02,7.0,53,68,6.0,12.0,1,1,0,0,-9,0,1,0,0,2,0.0,0.779412,-2,-15,-7.5,1979-09-02,1.0,False,34.0,ATL,40.0,NO,-5.0,32.0,1.0,16.0,1979-12-16,-105.0,34.0,40.0,-11.0,42.0,0.0,1.0,0.0,0.0,-6.0,0.0,1.0,0.0,0.0,1.0,0.0,0.850000,-1.0,-6.0,-6.0
36,1979-09-09,1979,2,False,NYJ,3,NE,56,NE,-8.0,42.0,0,1.0,1979-09-02,7.0,25,81,45.0,17.0,1,1,0,0,-53,0,1,0,0,2,0.0,0.308642,-2,-56,-28.0,1979-09-02,1.0,False,22.0,CLE,25.0,NYJ,-2.0,41.0,1.0,16.0,1979-12-16,-105.0,22.0,25.0,-5.0,6.0,0.0,1.0,0.0,0.0,-3.0,0.0,1.0,0.0,0.0,1.0,0.0,0.880000,-1.0,-3.0,-3.0
37,1979-09-09,1979,2,False,OAK,10,LAC,30,LAC,-3.0,42.0,0,1.0,1979-09-02,7.0,34,47,17.0,-2.0,1,0,0,0,-20,0,1,0,1,1,1.0,0.723404,0,-13,-6.5,1979-09-02,1.0,False,24.0,LAR,17.0,LAR,-4.0,36.5,0.0,16.0,1979-12-15,-104.0,24.0,17.0,-11.0,4.5,0.0,1.0,0.0,0.0,7.0,1.0,0.0,0.0,1.0,0.0,1.0,1.411765,1.0,7.0,7.0
38,1979-09-09,1979,2,False,SEA,10,MIA,19,MIA,-7.0,40.5,0,1.0,1979-09-02,7.0,26,52,2.0,-11.5,1,0,0,0,-9,0,1,0,0,2,0.0,0.500000,-2,-26,-13.0,1979-09-02,1.0,False,16.0,LAC,33.0,SEA,-2.0,42.5,1.0,16.0,1979-12-16,-105.0,16.0,33.0,-19.0,6.5,0.0,1.0,0.0,0.0,-17.0,0.0,1.0,0.0,0.0,1.0,0.0,0.484848,-1.0,-17.0,-17.0
40,1979-09-09,1979,2,False,TEN,7,PIT,38,PIT,-6.0,37.0,0,1.0,1979-09-02,7.0,36,65,25.0,8.0,1,1,0,0,-31,0,1,0,1,1,1.0,0.553846,0,-29,-14.5,1979-09-02,1.0,False,29.0,WAS,27.0,TEN,-4.0,33.0,0.0,16.0,1979-12-16,-105.0,29.0,27.0,-2.0,23.0,0.0,1.0,0.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,1.0,1.074074,1.0,2.0,2.0
42,1979-09-09,1979,2,False,BUF,51,CIN,24,CIN,-3.0,34.0,1,1.0,1979-09-02,7.0,58,33,-30.0,41.0,0,1,0,0,27,1,0,0,1,1,1.0,1.757576,0,25,12.5,1979-09-02,1.0,False,7.0,MIA,9.0,MIA,-5.0,39.0,1.0,16.0,1979-12-16,-105.0,7.0,9.0,-3.0,-23.0,0.0,0.0,0.0,0.0,-2.0,0.0,1.0,0.0,0.0,1.0,0.0,0.777778,-1.0,-2.0,-2.0
43,1979-09-09,1979,2,False,CHI,26,MIN,7,CHI,-6.0,31.5,1,1.0,1979-09-02,7.0,32,10,13.0,1.5,1,1,0,0,19,1,0,0,2,0,2.0,3.200000,2,22,11.0,1979-09-02,1.0,False,6.0,GB,3.0,CHI,-3.0,31.0,1.0,16.0,1979-12-16,-105.0,6.0,3.0,0.0,-22.0,0.0,0.0,1.0,0.0,3.0,1.0,0.0,0.0,1.0,0.0,1.0,2.000000,1.0,3.0,3.0
44,1979-09-06,1979,2,False,DEN,9,LAR,13,DEN,-2.0,31.5,1,1.0,1979-09-02,4.0,19,13,-6.0,-9.5,0,0,0,0,-4,0,1,0,1,1,1.0,1.461538,0,6,3.0,1979-09-02,1.0,False,10.0,CIN,0.0,DEN,-3.0,31.5,1.0,16.0,1979-12-16,-105.0,10.0,0.0,7.0,-21.5,1.0,0.0,0.0,0.0,10.0,1.0,0.0,0.0,1.0,0.0,1.0,10.000000,1.0,10.0,10.0
46,1979-09-09,1979,2,False,GB,28,NO,19,GB,-3.0,35.0,1,1.0,1979-09-02,7.0,31,25,6.0,12.0,1,1,0,0,9,1,0,0,1,1,1.0,1.240000,0,6,3.0,1979-09-02,1.0,False,3.0,CHI,6.0,CHI,-3.0,31.0,0.0,16.0,1979-12-15,-104.0,3.0,6.0,0.0,-22.0,0.0,0.0,1.0,0.0,-3.0,0.0,1.0,0.0,0.0,1.0,0.0,0.500000,-1.0,-3.0,-3.0
49,1979-09-09,1979,2,False,LAC,30,OAK,10,LAC,-3.0,42.0,1,1.0,1979-09-02,7.0,63,26,17.0,-2.0,1,0,0,0,20,1,0,0,2,0,2.0,2.423077,2,37,18.5,1979-09-02,1.0,False,33.0,SEA,16.0,SEA,-2.0,42.5,0.0,16.0,1979-12-16,-105.0,33.0,16.0,-19.0,6.5,0.0,1.0,0.0,0.0,17.0,1.0,0.0,0.0,1.0,0.0,1.0,2.062500,1.0,17.0,17.0
50,1979-09-09,1979,2,False,MIA,19,SEA,10,MIA,-7.0,40.5,1,1.0,1979-09-02,7.0,28,17,2.0,-11.5,1,0,0,0,9,1,0,0,2,0,2.0,1.647059,2,11,5.5,1979-09-02,1.0,False,9.0,BUF,7.0,MIA,-5.0,39.0,0.0,16.0,1979-12-16,-105.0,9.0,7.0,-3.0,-23.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,1.0,1.285714,1.0,2.0,2.0
51,1979-09-09,1979,2,False,NE,56,NYJ,3,NE,-8.0,42.0,1,1.0,1979-09-03,6.0,69,19,45.0,17.0,1,1,0,0,53,1,0,0,1,1,1.0,3.631579,0,50,25.0,1979-09-03,1.0,False,13.0,PIT,16.0,PIT,-2.0,37.0,1.0,16.0,1979-12-16,-104.0,13.0,16.0,1.0,-8.0,1.0,0.0,0.0,0.0,-3.0,0.0,1.0,0.0,0.0,1.0,0.0,0.812500,-1.0,-3.0,-3.0
52,1979-09-09,1979,2,False,NYG,14,ARI,27,ARI,-3.0,36.0,1,1.0,1979-09-02,7.0,31,50,10.0,5.0,1,1,0,0,-13,0,1,0,0,2,0.0,0.620000,-2,-19,-9.5,1979-09-02,1.0,False,17.0,PHI,23.0,PHI,-7.0,31.5,0.0,16.0,1979-12-16,-105.0,17.0,23.0,-1.0,8.5,0.0,1.0,0.0,0.0,-6.0,0.0,1.0,0.0,0.0,1.0,0.0,0.739130,-1.0,-6.0,-6.0
53,1979-09-10,1979,2,False,PHI,10,ATL,14,PHI,-4.0,35.5,1,1.0,1979-09-02,8.0,33,31,-8.0,-11.5,0,0,0,0,-4,0,1,0,1,1,1.0,1.064516,0,2,1.0,1979-09-02,1.0,False,23.0,NYG,17.0,PHI,-7.0,31.5,1.0,16.0,1979-12-16,-105.0,23.0,17.0,-1.0,8.5,0.0,1.0,0.0,0.0,6.0,1.0,0.0,0.0,1.0,0.0,1.0,1.352941,1.0,6.0,6.0

In [674]:
print(df.info(verbose=True))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18002 entries, 28 to 19489
Data columns (total 66 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               18002 non-null  datetime64[ns]
 1   season             18002 non-null  int64
 2   week               18002 non-null  int64
 3   playoff            18002 non-null  bool
 4   team_id            18002 non-null  object
 5   team_score         18002 non-null  int64
 6   opponent_id        18002 non-null  object
 7   opponent_score     18002 non-null  int64
 8   favorite           18002 non-null  object
 9   spread             18002 non-null  float64
 10  overunder          18002 non-null  float64
 11  home               18002 non-null  int64
 12  prev_week          18002 non-null  float64
 13  prev_date          18002 non-null  datetime64[ns]
 14  days_since         18002 non-null  float64
 15  points_for         18002 non-null  int64
 16  points_against     18002 non-null  int64
 17  covered_by         18002 non-null  float64
 18  covered_over_by    18002 non-null  float64
 19  covered            18002 non-null  int32
 20  covered_over       18002 non-null  int32
 21  push               18002 non-null  int32
 22  push_over          18002 non-null  int32
 23  win_by             18002 non-null  int64
 24  win                18002 non-null  int32
 25  loss               18002 non-null  int32
 26  tie                18002 non-null  int32
 27  total_wins         18002 non-null  int32
 28  total_losses       18002 non-null  int32
 29  win_loss_ratio     18002 non-null  float64
 30  pfa_ratio          18002 non-null  float64
 31  net_wins           18002 non-null  int32
 32  net_pfa            18002 non-null  int64
 33  net_pfa_avg        18002 non-null  float64
 34  date_p             18002 non-null  datetime64[ns]
 35  week_p             18002 non-null  float64
 36  playoff_p          18002 non-null  object
 37  team_score_p       18002 non-null  float64
 38  opponent_id_p      18002 non-null  object
 39  opponent_score_p   18002 non-null  float64
 40  favorite_p         18002 non-null  object
 41  spread_p           18002 non-null  float64
 42  overunder_p        18002 non-null  float64
 43  home_p             18002 non-null  float64
 44  prev_week_p        18001 non-null  float64
 45  prev_date_p        18001 non-null  datetime64[ns]
 46  days_since_p       18001 non-null  float64
 47  points_for_p       18002 non-null  float64
 48  points_against_p   18002 non-null  float64
 49  covered_by_p       18002 non-null  float64
 50  covered_over_by_p  18002 non-null  float64
 51  covered_p          18002 non-null  float64
 52  covered_over_p     18002 non-null  float64
 53  push_p             18002 non-null  float64
 54  push_over_p        18002 non-null  float64
 55  win_by_p           18002 non-null  float64
 56  win_p              18002 non-null  float64
 57  loss_p             18002 non-null  float64
 58  tie_p              18002 non-null  float64
 59  total_wins_p       18002 non-null  float64
 60  total_losses_p     18002 non-null  float64
 61  win_loss_ratio_p   18002 non-null  float64
 62  pfa_ratio_p        18002 non-null  float64
 63  net_wins_p         18002 non-null  float64
 64  net_pfa_p          18002 non-null  float64
 65  net_pfa_avg_p      18002 non-null  float64
dtypes: bool(1), datetime64[ns](4), float64(36), int32(10), int64(9), object(6)
memory usage: 8.4+ MB
None

In [675]:
#identify teams that lost outright in previous week despite being favored
df['bounce_candidate'] = np.where((df['team_id'] == df['favorite_p']) & (df['win_p'] == 0), 1,0)

In [676]:
df['bounce_candidate'].value_counts()

0    14962
1     3040
Name: bounce_candidate, dtype: int64

In [677]:
pd.set_option("display.max.columns", None)
df.loc[(df['season'] == 1999) & (df['team_id'] == 'DEN')]

,date,season,week,playoff,team_id,team_score,opponent_id,opponent_score,favorite,spread,overunder,home,prev_week,prev_date,days_since,points_for,points_against,covered_by,covered_over_by,covered,covered_over,push,push_over,win_by,win,loss,tie,total_wins,total_losses,win_loss_ratio,pfa_ratio,net_wins,net_pfa,net_pfa_avg,date_p,week_p,playoff_p,team_score_p,opponent_id_p,opponent_score_p,favorite_p,spread_p,overunder_p,home_p,prev_week_p,prev_date_p,days_since_p,points_for_p,points_against_p,covered_by_p,covered_over_by_p,covered_p,covered_over_p,push_p,push_over_p,win_by_p,win_p,loss_p,tie_p,total_wins_p,total_losses_p,win_loss_ratio_p,pfa_ratio_p,net_wins_p,net_pfa_p,net_pfa_avg_p,bounce_candidate
8819,1999-09-19,1999,2,False,DEN,10,KC,26,DEN,-3.5,40.5,0,1.0,1999-09-13,6.0,31,64,-19.5,-4.5,0,0,0,0,-16,0,1,0,0,2,0.000000,0.484375,-2,-33,-16.500000,1999-09-13,1.0,False,21.0,MIA,38.0,DEN,-6.0,43.0,1.0,17.0,2000-01-02,-111.0,21.0,38.0,-23.0,16.0,0.0,1.0,0.0,0.0,-17.0,0.0,1.0,0.0,0.0,1.0,0.000000,0.552632,-1.0,-17.0,-17.000000,1
8850,1999-09-26,1999,3,False,DEN,10,TB,13,TB,-2.5,38.0,0,2.0,1999-09-19,7.0,41,77,0.5,-15.0,1,0,0,0,-3,0,1,0,0,3,0.000000,0.532468,-3,-36,-12.000000,1999-09-19,2.0,False,10.0,KC,26.0,DEN,-3.5,40.5,0.0,1.0,1999-09-13,6.0,31.0,64.0,-19.5,-4.5,0.0,0.0,0.0,0.0,-16.0,0.0,1.0,0.0,0.0,2.0,0.000000,0.484375,-2.0,-33.0,-16.500000,1
8893,1999-10-03,1999,4,False,DEN,13,NYJ,21,DEN,-5.5,40.0,1,3.0,1999-09-26,7.0,54,98,-13.5,-6.0,0,0,0,0,-8,0,1,0,0,4,0.000000,0.551020,-4,-44,-11.000000,1999-09-26,3.0,False,10.0,TB,13.0,TB,-2.5,38.0,0.0,2.0,1999-09-19,7.0,41.0,77.0,0.5,-15.0,1.0,0.0,0.0,0.0,-3.0,0.0,1.0,0.0,0.0,3.0,0.000000,0.532468,-3.0,-36.0,-12.000000,0
8907,1999-10-10,1999,5,False,DEN,16,OAK,13,OAK,-7.0,38.0,0,4.0,1999-10-03,7.0,70,111,-10.0,-9.0,0,0,0,0,3,1,0,0,1,4,0.250000,0.630631,-3,-41,-8.200000,1999-10-03,4.0,False,13.0,NYJ,21.0,DEN,-5.5,40.0,1.0,3.0,1999-09-26,7.0,54.0,98.0,-13.5,-6.0,0.0,0.0,0.0,0.0,-8.0,0.0,1.0,0.0,0.0,4.0,0.000000,0.551020,-4.0,-44.0,-11.000000,1
8949,1999-10-17,1999,6,False,DEN,31,GB,10,GB,-3.5,40.0,1,5.0,1999-10-10,7.0,101,121,-24.5,1.0,0,1,0,0,21,1,0,0,2,4,0.500000,0.834711,-2,-20,-3.333333,1999-10-10,5.0,False,16.0,OAK,13.0,OAK,-7.0,38.0,0.0,4.0,1999-10-03,7.0,70.0,111.0,-10.0,-9.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,1.0,4.0,0.250000,0.630631,-3.0,-41.0,-8.200000,0
8963,1999-10-24,1999,7,False,DEN,23,NE,24,NE,-3.5,40.5,0,6.0,1999-10-17,7.0,124,145,-2.5,6.5,0,1,0,0,-1,0,1,0,2,5,0.400000,0.855172,-3,-21,-3.000000,1999-10-17,6.0,False,31.0,GB,10.0,GB,-3.5,40.0,1.0,5.0,1999-10-10,7.0,101.0,121.0,-24.5,1.0,0.0,1.0,0.0,0.0,21.0,1.0,0.0,0.0,2.0,4.0,0.500000,0.834711,-2.0,-20.0,-3.333333,0
9004,1999-10-31,1999,8,False,DEN,20,MIN,23,MIN,-2.5,45.0,1,7.0,1999-10-24,7.0,144,168,0.5,-2.0,1,0,0,0,-3,0,1,0,2,6,0.333333,0.857143,-4,-24,-3.000000,1999-10-24,7.0,False,23.0,NE,24.0,NE,-3.5,40.5,0.0,6.0,1999-10-17,7.0,124.0,145.0,-2.5,6.5,0.0,1.0,0.0,0.0,-1.0,0.0,1.0,0.0,2.0,5.0,0.400000,0.855172,-3.0,-21.0,-3.000000,0
9045,1999-11-14,1999,10,False,DEN,17,SEA,20,SEA,-5.5,41.0,0,9.0,1999-11-07,7.0,194,205,-2.5,-4.0,0,0,0,0,-3,0,1,0,3,7,0.428571,0.946341,-4,-11,-1.100000,1999-11-07,9.0,False,33.0,LAC,17.0,PICK,0.0,35.5,0.0,8.0,1999-10-31,7.0,177.0,185.0,-16.0,14.5,0.0,1.0,0.0,0.0,16.0,1.0,0.0,0.0,3.0,6.0,0.500000,0.956757,-3.0,-8.0,-0.888889,0
9090,1999-11-22,1999,11,False,DEN,27,OAK,21,DEN,-1.5,37.0,1,10.0,1999-11-14,8.0,221,226,4.5,11.0,1,1,0,0,6,1,0,0,4,7,0.571429,0.977876,-3,-5,-0.454545,1999-11-14,10.0,False,17.0,SEA,20.0,SEA,-5.5,41.0,0.0,9.0,1999-11-07,7.0,194.0,205.0,-2.5,-4.0,0.0,0.0,0.0,0.0,-3.0,0.0,1.0,0.0,3.0,7.0,0.428571,0.946341,-4.0,-11.0,-1.100000,0
9153,1999-12-05,1999,13,False,DEN,10,KC,16,DEN,-3.5,38.5,1,11.0,1999-11-22,13.0,231,242,-9.5,-12.5,0,0,0,0,-6,0,1,0,4,8,0.500000,0.954545,-4,-11,-0.846154,1999-11-22,11.0,False,27.0,OAK,21.0,DEN,-1.5,37.0,1.0,10.0,1999-11-14,8.0,221.0,226.0,4.5,11.0,1.0,1.0,0.0,0.0,6.0,1.0,0.0,0.0,4.0,7.0,0.571429,0.977876,-3.0,-5.0,-0.454545,0
9167,1999-12-13,1999,14,False,DEN,24,JAX,27,JAX,-9.0,37.5,0,13.0,1999-12-05,8.0,255,269,-6.0,13.5,0,1,0,0,-3,0,1,0,4,9,0.444444,0.947955,-5,-14,-1.000000,1999-12-05,13.0,False,10.0,KC,16.0,DEN,-3.5,38.5,1.0,11.0,1999-11-22,13.0,231.0,242.0,-9.5,-12.5,0.0,0.0,0.0,0.0,-6.0,0.0,1.0,0.0,4.0,8.0,0.500000,0.954545,-4.0,-11.0,-0.846154,1
9213,1999-12-19,1999,15,False,DEN,36,SEA,30,DEN,-1.5,39.0,1,14.0,1999-12-13,6.0,291,299,4.5,27.0,1,1,0,0,6,1,0,0,5,9,0.555556,0.973244,-4,-8,-0.533333,1999-12-13,14.0,False,24.0,JAX,27.0,JAX,-9.0,37.5,0.0,13.0,1999-12-05,8.0,255.0,269.0,-6.0,13.5,0.0,1.0,0.0,0.0,-3.0,0.0,1.0,0.0,4.0,9.0,0.444444,0.947955,-5.0,-14.0,-1.000000,0
9228,1999-12-25,1999,16,False,DEN,17,DET,7,DET,-4.5,43.5,0,15.0,1999-12-19,6.0,308,306,-14.5,-19.5,0,0,0,0,10,1,0,0,6,9,0.666667,1.006536,-3,2,0.125000,1999-12-19,15.0,False,36.0,SEA,30.0,DEN,-1.5,39.0,1.0,14.0,1999-12-13,6.0,291.0,299.0,4.5,27.0,1.0,1.0,0.0,0.0,6.0,1.0,0.0,0.0,5.0,9.0,0.555556,0.973244,-4.0,-8.0,-0.533333,0
9272,2000-01-02,1999,17,False,DEN,6,LAC,12,DEN,-7.0,37.5,1,16.0,1999-12-25,8.0,314,318,-13.0,-19.5,0,0,0,0,-6,0,1,0,6,10,0.600000,0.987421,-4,-4,-0.235294,1999-12-25,16.0,False,17.0,DET,7.0,DET,-4.5,43.5,0.0,15.0,1999-12-19,6.0,308.0,306.0,-14.5,-19.5,0.0,0.0,0.0,0.0,10.0,1.0,0.0,0.0,6.0,9.0,0.666667,1.006536,-3.0,2.0,0.125000,0

In [678]:
df = df.dropna()
df.shape

(18001, 67)

In [679]:
print(df[['prev_date','date_p']])

       prev_date     date_p
29    1979-09-02 1979-09-02
30    1979-09-02 1979-09-02
32    1979-09-02 1979-09-02
33    1979-09-02 1979-09-02
34    1979-09-02 1979-09-02
...          ...        ...
19485 2019-12-23 2019-12-23
19486 2019-12-21 2019-12-21
19487 2019-12-22 2019-12-22
19488 2019-12-22 2019-12-22
19489 2019-12-21 2019-12-21

[18001 rows x 2 columns]

In [680]:
df['bye']=df['week']-df['prev_week']

In [681]:
df['bye'].value_counts()

 1.0     16988
 2.0       946
 5.0        28
 9.0        26
-15.0        7
 0.0         6
Name: bye, dtype: int64

In [682]:
#remove unusual cases of teams suspension, etc. Teams should play all weeks except one "bye" week
keeps = [1, 2]

df = df[df.bye.isin(keeps)]

In [683]:
df.columns

Index(['date', 'season', 'week', 'playoff', 'team_id', 'team_score',
       'opponent_id', 'opponent_score', 'favorite', 'spread', 'overunder',
       'home', 'prev_week', 'prev_date', 'days_since', 'points_for',
       'points_against', 'covered_by', 'covered_over_by', 'covered',
       'covered_over', 'push', 'push_over', 'win_by', 'win', 'loss', 'tie',
       'total_wins', 'total_losses', 'win_loss_ratio', 'pfa_ratio', 'net_wins',
       'net_pfa', 'net_pfa_avg', 'date_p', 'week_p', 'playoff_p',
       'team_score_p', 'opponent_id_p', 'opponent_score_p', 'favorite_p',
       'spread_p', 'overunder_p', 'home_p', 'prev_week_p', 'prev_date_p',
       'days_since_p', 'points_for_p', 'points_against_p', 'covered_by_p',
       'covered_over_by_p', 'covered_p', 'covered_over_p', 'push_p',
       'push_over_p', 'win_by_p', 'win_p', 'loss_p', 'tie_p', 'total_wins_p',
       'total_losses_p', 'win_loss_ratio_p', 'pfa_ratio_p', 'net_wins_p',
       'net_pfa_p', 'net_pfa_avg_p', 'bounce_candidate', 'bye'],
      dtype='object')

In [684]:
#cull useless columns
df = df[['date', 'season', 'week', 'team_id', 'team_score',
       'opponent_id', 'opponent_score', 'favorite', 'spread', 'overunder',
       'home', 'prev_week','days_since', 'points_for',
       'points_against', 'covered_by', 'covered_over_by', 'covered',
       'covered_over', 'push', 'push_over', 'win_by', 'win', 'loss', 'tie',
       'total_wins', 'total_losses', 'win_loss_ratio', 'pfa_ratio', 'net_wins',
       'net_pfa', 'net_pfa_avg', 'date_p', 'favorite_p', 'home_p', 'covered_by_p',
       'covered_over_by_p', 'covered_p', 'covered_over_p', 'push_p',
       'push_over_p', 'win_by_p', 'win_p', 'loss_p', 'tie_p', 'bounce_candidate', 'bye']]

In [685]:
#break out date info
df['day_of_week'] = df['date'].dt.day_name()
df['month'] = df['date'].dt.month_name()

In [686]:
#scan for strange or missing values
for i in df.columns:
    x = df[i].value_counts()
    print("Column name is:",i,"and it value is:",x)
    print()

Column name is: date and it value is: 2010-01-03    32
2013-12-29    32
2018-12-30    32
2017-01-01    32
2017-12-31    32
              ..
2012-09-27     2
2005-11-21     2
1997-11-24     2
1989-11-27     2
1992-09-14     1
Name: date, Length: 1552, dtype: int64

Column name is: season and it value is: 2018    480
2019    480
2014    480
2008    480
2011    480
2009    480
2002    478
2017    478
2016    476
2013    476
2006    476
2012    476
2007    476
2003    474
2004    472
2015    472
2005    470
2010    470
2001    461
1999    459
2000    457
1995    444
1996    444
1998    444
1997    442
1991    418
1994    416
1993    416
1980    416
1986    414
1989    414
1992    412
1990    412
1988    408
1981    406
1984    406
1985    404
1983    402
1979    401
1987    274
1982    190
Name: season, dtype: int64

Column name is: week and it value is: 16    1222
15    1216
13    1214
14    1212
12    1206
2     1198
11    1148
3     1120
10    1104
9     1068
4     1061
8     1060
5     1050
6     1045
7     1038
17     948
18      24
Name: week, dtype: int64

Column name is: team_id and it value is: ARI    597
MIN    597
NYG    596
DET    596
PHI    596
PIT    595
DAL    595
MIA    595
OAK    595
SF     594
TB     594
ATL    594
GB     594
TEN    594
SEA    594
KC     593
WAS    593
NE     593
CHI    592
NYJ    592
NO     592
IND    592
LAR    592
BUF    591
LAC    590
CIN    590
DEN    589
CLE    545
JAX    372
CAR    368
BAL    355
HOU    269
Name: team_id, dtype: int64

Column name is: team_score and it value is: 17    1353
20    1212
24    1164
10    1042
27     938
13     927
14     863
31     788
21     767
23     766
7      683
16     613
28     543
34     523
30     481
3      440
6      378
26     370
19     366
38     365
0      295
35     287
9      264
37     241
22     237
33     199
41     192
12     173
29     165
15     152
25     130
42     123
45     108
18      94
36      85
44      80
32      80
40      74
48      57
43      40
11      35
39      32
49      32
8       29
51      25
47      24
52      20
55      13
5       11
50      10
56      10
46       9
54       6
59       6
2        3
58       3
53       2
57       2
61       2
62       2
Name: team_score, dtype: int64

Column name is: opponent_id and it value is: ARI    599
PHI    597
MIA    597
MIN    596
DAL    595
PIT    595
TB     595
NYG    595
OAK    595
TEN    595
DET    595
NE     594
SF     594
SEA    594
GB     594
KC     594
ATL    594
WAS    593
NYJ    592
NO     592
IND    592
CHI    591
BUF    591
LAR    590
LAC    590
CIN    590
DEN    588
CLE    543
JAX    372
CAR    368
BAL    355
HOU    269
Name: opponent_id, dtype: int64

Column name is: opponent_score and it value is: 17    1352
20    1212
24    1161
10    1042
27     940
13     927
14     861
31     787
21     767
23     765
7      682
16     613
28     543
34     525
30     481
3      440
6      378
26     370
19     367
38     364
0      296
35     287
9      264
37     241
22     237
33     199
41     192
12     173
29     166
15     152
25     130
42     123
45     108
18      94
36      85
32      81
44      80
40      74
48      58
43      41
11      35
39      32
49      32
8       29
51      25
47      24
52      20
55      13
5       11
50      10
56      10
46       9
54       6
59       6
2        3
58       3
53       2
57       2
61       2
62       2
Name: opponent_score, dtype: int64

Column name is: favorite and it value is: PIT    796
NE     768
DAL    756
DEN    751
SF     736
GB     696
PHI    677
MIN    658
MIA    643
NO     614
NYG    612
LAC    605
SEA    604
KC     589
OAK    574
TEN    571
WAS    570
BUF    558
LAR    558
CHI    556
ATL    552
IND    544
NYJ    526
CIN    480
TB     443
DET    440
BAL    416
ARI    385
CLE    380
CAR    356
JAX    302
HOU    218
Name: favorite, dtype: int64

Column name is: spread and it value is: -3.0     2795
-3.5     1432
-7.0     1293
-2.5     1159
-4.0     1004
-6.0      979
-1.0      901
-6.5      881
-2.0      808
-4.5      616
-5.5      606
-5.0      575
-7.5      560
-1.5      558
-10.0     520
-9.0      454
-8.0      410
-9.5      346
-8.5      295
-10.5     284
-11.0     216
-13.0     210
-13.5     192
-14.0     162
-12.0     122
-11.5     108
-14.5     102
-12.5      96
-17.0      48
-15.0      44
-16.0      36
-16.5      34
-15.5      30
-18.0      16
-17.5      10
-20.0       6
-20.5       4
-19.0       4
-18.5       4
-24.0       2
-22.5       2
-24.5       2
-21.5       2
-26.5       2
-19.5       2
-21.0       2
Name: spread, dtype: int64

Column name is: overunder and it value is: 41.0    1066
42.0     978
44.0     970
43.0     905
40.0     898
        ...
63.0       2
63.5       2
30.5       2
29.5       2
57.5       2
Name: overunder, Length: 67, dtype: int64

Column name is: home and it value is: 1    8967
0    8967
Name: home, dtype: int64

Column name is: prev_week and it value is: 15.0    1222
13.0    1216
14.0    1210
1.0     1205
12.0    1202
11.0    1178
2.0     1161
3.0     1114
10.0    1106
9.0     1072
4.0     1072
7.0     1068
8.0     1055
5.0     1045
6.0     1039
16.0     945
17.0      24
Name: prev_week, dtype: int64

Column name is: days_since and it value is: 7.0     12993
6.0      1551
8.0      1289
14.0      766
4.0       512
10.0      505
15.0       87
11.0       86
13.0       83
9.0        38
5.0        21
21.0        3
Name: days_since, dtype: int64

Column name is: points_for and it value is: 140    81
88     81
104    79
145    74
164    74
       ..
486     1
518     1
471     1
495     1
535     1
Name: points_for, Length: 516, dtype: int64

Column name is: points_against and it value is: 187    83
47     81
257    77
118    75
44     74
       ..
512     1
473     1
457     1
456     1
487     1
Name: points_against, Length: 473, dtype: int64

Column name is: covered_by and it value is:  0.0     504
-6.0     446
-4.0     376
 4.0     360
 1.0     348
        ...
 50.5      2
 41.0      2
 45.0      2
-52.0      2
 45.5      2
Name: covered_by, Length: 178, dtype: int64

Column name is: covered_over_by and it value is: -3.0     390
 1.0     352
-8.0     352
-4.0     346
 3.0     344
        ...
 48.0      2
-21.6      2
 52.0      2
-38.0      2
-39.0      2
Name: covered_over_by, Length: 179, dtype: int64

Column name is: covered and it value is: 0    9508
1    8426
Name: covered, dtype: int64

Column name is: covered_over and it value is: 0    9258
1    8676
Name: covered_over, dtype: int64

Column name is: push and it value is: 0    17430
1      504
Name: push, dtype: int64

Column name is: push_over and it value is: 0    17596
1      338
Name: push_over, dtype: int64

Column name is: win_by and it value is: -3     1361
 3     1360
 7      752
-7      752
-10     529
       ...
 58       1
-53       1
 59       1
-52       1
 55       1
Name: win_by, Length: 109, dtype: int64

Column name is: win and it value is: 0    8990
1    8944
Name: win, dtype: int64

Column name is: loss and it value is: 0    8984
1    8950
Name: loss, dtype: int64

Column name is: tie and it value is: 0    17894
1       40
Name: tie, dtype: int64

Column name is: total_wins and it value is: 2     2524
3     2400
4     2245
1     2019
5     1916
6     1581
7     1353
8     1012
0      908
9      767
10     530
11     345
12     190
13     105
14      31
15       7
16       1
Name: total_wins, dtype: int64

Column name is: total_losses and it value is: 2     2656
3     2418
4     2217
1     1985
5     1934
6     1635
7     1303
8     1000
0      848
9      736
10     498
11     330
12     212
13      98
14      50
15      12
16       2
Name: total_losses, dtype: int64

Column name is: win_loss_ratio and it value is: 1.000000     2153
2.000000     1469
0.500000     1076
0.000000      908
3.000000      860
             ...
0.071429       14
14.000000      11
0.066667       10
15.000000       7
16.000000       1
Name: win_loss_ratio, Length: 81, dtype: int64

Column name is: pfa_ratio and it value is: 1.000000    154
1.333333     36
1.500000     33
0.833333     33
1.250000     32
           ...
1.105802      1
1.939394      1
1.105691      1
1.231746      1
1.582915      1
Name: pfa_ratio, Length: 11873, dtype: int64

Column name is: net_wins and it value is:  0     2149
 2     1815
-2     1739
 1     1736
-1     1719
 3     1317
-3     1164
 4      994
-4      907
 5      642
-5      641
-6      521
 6      505
-7      352
 7      328
-8      278
 8      272
-9      162
 9      153
-10     126
 10     126
-11      67
-12      58
 11      58
 12      40
-13      21
 13      15
-14      14
 14       9
-15       2
-16       2
 16       1
 15       1
Name: net_wins, dtype: int64

Column name is: net_pfa and it value is:  0      154
-4      151
 1      147
 7      147
 6      146
       ...
 210      1
 226      1
-238      1
 258      1
-225      1
Name: net_pfa, Length: 476, dtype: int64

Column name is: net_pfa_avg and it value is:  3.000000     176
-2.000000     158
-3.000000     154
 0.000000     154
 1.000000     148
             ...
-11.812500      1
 18.187500      1
-12.937500      1
 11.461538      1
 12.900000      1
Name: net_pfa_avg, Length: 2654, dtype: int64

Column name is: date_p and it value is: 2009-09-27    30
2004-12-05    30
2003-12-07    30
2003-09-14    30
2011-10-02    30
              ..
1994-09-12     1
1992-09-21     1
1984-11-29     1
2006-11-27     1
1996-09-02     1
Name: date_p, Length: 1570, dtype: int64

Column name is: favorite_p and it value is: PIT     790
NE      760
DEN     751
DAL     747
SF      721
GB      689
PHI     687
MIN     652
MIA     619
NO      603
NYG     600
SEA     593
LAC     590
KC      578
CHI     568
LAR     563
WAS     562
BUF     551
OAK     549
TEN     547
ATL     537
IND     526
NYJ     522
CIN     470
DET     437
TB      432
BAL     399
ARI     383
CLE     380
CAR     348
JAX     306
PICK    260
HOU     214
Name: favorite_p, dtype: int64

Column name is: home_p and it value is: 1.0    8970
0.0    8964
Name: home_p, dtype: int64

Column name is: covered_by_p and it value is:  0.0     527
-6.0     452
-4.0     380
 4.0     365
 1.0     362
        ...
 45.5      2
-38.5      2
 42.5      2
 46.0      2
 44.0      1
Name: covered_by_p, Length: 179, dtype: int64

Column name is: covered_over_by_p and it value is: -3.0     390
-8.0     350
 1.0     348
 0.0     345
-4.0     338
        ...
 54.5      2
 3.4       2
 47.0      2
-32.5      2
 46.5      2
Name: covered_over_by_p, Length: 179, dtype: int64

Column name is: covered_p and it value is: 0.0    9539
1.0    8395
Name: covered_p, dtype: int64

Column name is: covered_over_p and it value is: 0.0    9297
1.0    8637
Name: covered_over_p, dtype: int64

Column name is: push_p and it value is: 0.0    17407
1.0      527
Name: push_p, dtype: int64

Column name is: push_over_p and it value is: 0.0    17589
1.0      345
Name: push_over_p, dtype: int64

Column name is: win_by_p and it value is:  3.0     1375
-3.0     1373
 7.0      764
-7.0      756
 6.0      530
         ...
-52.0       1
-53.0       1
-55.0       1
-58.0       1
 53.0       1
Name: win_by_p, Length: 111, dtype: int64

Column name is: win_p and it value is: 0.0    8979
1.0    8955
Name: win_p, dtype: int64

Column name is: loss_p and it value is: 0.0    8996
1.0    8938
Name: loss_p, dtype: int64

Column name is: tie_p and it value is: 0.0    17893
1.0       41
Name: tie_p, dtype: int64

Column name is: bounce_candidate and it value is: 0    14911
1     3023
Name: bounce_candidate, dtype: int64

Column name is: bye and it value is: 1.0    16988
2.0      946
Name: bye, dtype: int64

Column name is: day_of_week and it value is: Sunday      15740
Monday       1218
Thursday      558
Saturday      400
Friday         16
Tuesday         2
Name: day_of_week, dtype: int64

Column name is: month and it value is: November     4926
December     4926
October      4606
September    3150
January       326
Name: month, dtype: int64

In [687]:
df = pd.get_dummies(df, columns = ['day_of_week'], drop_first=True)
df = pd.get_dummies(df, columns = ['month'])

In [688]:
df = pd.get_dummies(df, columns = ['bye'])

In [689]:
df.head()

,date,season,week,team_id,team_score,opponent_id,opponent_score,favorite,spread,overunder,home,prev_week,days_since,points_for,points_against,covered_by,covered_over_by,covered,covered_over,push,push_over,win_by,win,loss,tie,total_wins,total_losses,win_loss_ratio,pfa_ratio,net_wins,net_pfa,net_pfa_avg,date_p,favorite_p,home_p,covered_by_p,covered_over_by_p,covered_p,covered_over_p,push_p,push_over_p,win_by_p,win_p,loss_p,tie_p,bounce_candidate,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,month_December,month_January,month_November,month_October,month_September,bye_1.0,bye_2.0
29,1979-09-10,1979,2,ATL,14,PHI,10,PHI,-4.0,35.5,0,1.0,8.0,54,44,-8.0,-11.5,0,0,0,0,4,1,0,0,2,0,2.0,1.227273,2,10,5.0,1979-09-02,NO,0.0,-11.0,42.0,0.0,1.0,0.0,0.0,6.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,1,1,0
30,1979-09-09,1979,2,CIN,24,BUF,51,CIN,-3.0,34.0,0,1.0,7.0,24,61,-30.0,41.0,0,1,0,0,-27,0,1,0,0,2,0.0,0.393443,-2,-37,-18.5,1979-09-02,DEN,0.0,7.0,-21.5,1.0,0.0,0.0,0.0,-10.0,0.0,1.0,0.0,0,0,0,1,0,0,0,0,0,0,1,1,0
32,1979-09-09,1979,2,DAL,21,SF,13,DAL,-13.0,39.0,0,1.0,7.0,43,34,-5.0,-5.0,0,0,0,0,8,1,0,0,2,0,2.0,1.264706,2,9,4.5,1979-09-02,DAL,0.0,-3.0,6.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0,0,0,1,0,0,0,0,0,0,1,1,0
33,1979-09-06,1979,2,LAR,13,DEN,9,DEN,-2.0,31.5,0,1.0,4.0,30,33,-6.0,-9.5,0,0,0,0,4,1,0,0,1,1,1.0,0.909091,0,-3,-1.5,1979-09-02,LAR,1.0,-11.0,4.5,0.0,1.0,0.0,0.0,-7.0,0.0,1.0,0.0,1,0,0,0,1,0,0,0,0,0,1,1,0
34,1979-09-09,1979,2,MIN,7,CHI,26,CHI,-6.0,31.5,0,1.0,7.0,35,48,13.0,1.5,1,1,0,0,-19,0,1,0,1,1,1.0,0.729167,0,-13,-6.5,1979-09-02,MIN,1.0,-1.0,18.0,0.0,1.0,0.0,0.0,6.0,1.0,0.0,0.0,0,0,0,1,0,0,0,0,0,0,1,1,0

In [690]:
#binarize favorite
#identify teams that lost outright in previous week despite being favored
df['fav'] = np.where(df['team_id'] == df['favorite'], 1,0)
df['fav_p'] = np.where(df['team_id'] == df['favorite_p'], 1,0)

In [691]:
#remove columns we aren't predicting or don't need in the current week
df.columns

Index(['date', 'season', 'week', 'team_id', 'team_score', 'opponent_id',
       'opponent_score', 'favorite', 'spread', 'overunder', 'home',
       'prev_week', 'days_since', 'points_for', 'points_against', 'covered_by',
       'covered_over_by', 'covered', 'covered_over', 'push', 'push_over',
       'win_by', 'win', 'loss', 'tie', 'total_wins', 'total_losses',
       'win_loss_ratio', 'pfa_ratio', 'net_wins', 'net_pfa', 'net_pfa_avg',
       'date_p', 'favorite_p', 'home_p', 'covered_by_p', 'covered_over_by_p',
       'covered_p', 'covered_over_p', 'push_p', 'push_over_p', 'win_by_p',
       'win_p', 'loss_p', 'tie_p', 'bounce_candidate', 'day_of_week_Monday',
       'day_of_week_Saturday', 'day_of_week_Sunday', 'day_of_week_Thursday',
       'day_of_week_Tuesday', 'month_December', 'month_January',
       'month_November', 'month_October', 'month_September', 'bye_1.0',
       'bye_2.0', 'fav', 'fav_p'],
      dtype='object')

In [694]:
df = df[['covered','week','spread', 'overunder', 'home','days_since','win_loss_ratio', 'pfa_ratio', 'net_wins', 'net_pfa', 'net_pfa_avg', 'home_p', 'covered_by_p', 'covered_over_by_p',
       'covered_p', 'covered_over_p','win_by_p',
       'win_p', 'loss_p', 'tie_p', 'bounce_candidate', 'day_of_week_Monday',
       'day_of_week_Saturday', 'day_of_week_Sunday', 'day_of_week_Thursday',
       'day_of_week_Tuesday', 'month_December', 'month_January',
       'month_November', 'month_October', 'month_September',
       'bye_2.0', 'fav', 'fav_p']]

In [695]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17934 entries, 29 to 19489
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   covered               17934 non-null  int32
 1   week                  17934 non-null  int64
 2   spread                17934 non-null  float64
 3   overunder             17934 non-null  float64
 4   home                  17934 non-null  int64
 5   days_since            17934 non-null  float64
 6   win_loss_ratio        17934 non-null  float64
 7   pfa_ratio             17934 non-null  float64
 8   net_wins              17934 non-null  int32
 9   net_pfa               17934 non-null  int64
 10  net_pfa_avg           17934 non-null  float64
 11  home_p                17934 non-null  float64
 12  covered_by_p          17934 non-null  float64
 13  covered_over_by_p     17934 non-null  float64
 14  covered_p             17934 non-null  float64
 15  covered_over_p        17934 non-null  float64
 16  win_by_p              17934 non-null  float64
 17  win_p                 17934 non-null  float64
 18  loss_p                17934 non-null  float64
 19  tie_p                 17934 non-null  float64
 20  bounce_candidate      17934 non-null  int32
 21  day_of_week_Monday    17934 non-null  uint8
 22  day_of_week_Saturday  17934 non-null  uint8
 23  day_of_week_Sunday    17934 non-null  uint8
 24  day_of_week_Thursday  17934 non-null  uint8
 25  day_of_week_Tuesday   17934 non-null  uint8
 26  month_December        17934 non-null  uint8
 27  month_January         17934 non-null  uint8
 28  month_November        17934 non-null  uint8
 29  month_October         17934 non-null  uint8
 30  month_September       17934 non-null  uint8
 31  bye_2.0               17934 non-null  uint8
 32  fav                   17934 non-null  int32
 33  fav_p                 17934 non-null  int32
dtypes: float64(15), int32(5), int64(3), uint8(11)
memory usage: 3.1 MB

In [708]:
df.columns

Index(['covered', 'week', 'spread', 'overunder', 'home', 'days_since',
       'win_loss_ratio', 'pfa_ratio', 'net_wins', 'net_pfa', 'net_pfa_avg',
       'home_p', 'covered_by_p', 'covered_over_by_p', 'covered_p',
       'covered_over_p', 'win_by_p', 'win_p', 'loss_p', 'tie_p',
       'bounce_candidate', 'day_of_week_Monday', 'day_of_week_Saturday',
       'day_of_week_Sunday', 'day_of_week_Thursday', 'day_of_week_Tuesday',
       'month_December', 'month_January', 'month_November', 'month_October',
       'month_September', 'bye_2.0', 'fav', 'fav_p'],
      dtype='object')

In [711]:
df_include = df[['week', 'spread', 'overunder', 'home', 'days_since',
       'win_loss_ratio', 'pfa_ratio', 'net_wins', 'net_pfa', 'net_pfa_avg',
       'home_p', 'covered_by_p', 'covered_over_by_p', 'covered_p',
       'covered_over_p', 'win_by_p', 'win_p', 'loss_p', 'tie_p',
       'bounce_candidate', 'day_of_week_Monday', 'day_of_week_Saturday',
       'day_of_week_Sunday', 'day_of_week_Thursday', 'day_of_week_Tuesday',
       'month_December', 'month_January', 'month_November', 'month_October',
       'month_September', 'bye_2.0', 'fav', 'fav_p']]

In [713]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_df = scaler.fit_transform(df_include)
scaled_df = pd.DataFrame(scaled_df,columns=df_include.columns)

In [714]:
scaled_df.head()

,week,spread,overunder,home,days_since,win_loss_ratio,pfa_ratio,net_wins,net_pfa,net_pfa_avg,home_p,covered_by_p,covered_over_by_p,covered_p,covered_over_p,win_by_p,win_p,loss_p,tie_p,bounce_candidate,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,month_December,month_January,month_November,month_October,month_September,bye_2.0,fav,fav_p
0,-1.643606,0.433028,-1.384394,-1.0,0.349187,0.278171,0.300870,0.487772,0.152590,0.701500,-1.000335,-0.810126,3.032757,-0.938121,1.037504,0.405173,1.001339,-0.996771,-0.047869,-0.450262,3.704610,-0.151039,-2.678453,-0.179202,-0.010561,-0.615378,-0.136067,-0.615378,-0.587868,2.16641,-0.23598,-0.999888,-0.986156
1,-1.643606,0.724263,-1.708168,-1.0,-0.207909,-0.906986,-1.319577,-0.490335,-0.570306,-2.598512,-1.000335,0.536283,-1.612355,1.065960,-0.963851,-0.676204,-0.998663,1.003239,-0.047869,-0.450262,-0.269934,-0.151039,0.373350,-0.179202,-0.010561,-0.615378,-0.136067,-0.615378,-0.587868,2.16641,-0.23598,1.000112,-0.986156
2,-1.643606,-2.188086,-0.628922,-1.0,-0.207909,0.278171,0.373617,0.487772,0.137209,0.631287,-1.000335,-0.211722,0.399308,-0.938121,1.037504,0.067243,1.001339,-0.996771,-0.047869,-0.450262,-0.269934,-0.151039,0.373350,-0.179202,-0.010561,-0.615378,-0.136067,-0.615378,-0.587868,2.16641,-0.23598,1.000112,1.014039
3,-1.643606,1.015498,-2.247792,-1.0,-1.879199,-0.314407,-0.317477,-0.001282,-0.047360,-0.211270,0.999665,-0.810126,0.289581,-0.938121,1.037504,-0.473445,-0.998663,1.003239,-0.047869,2.220927,-0.269934,-0.151039,-2.678453,5.580303,-0.010561,-0.615378,-0.136067,-0.615378,-0.587868,2.16641,-0.23598,-0.999888,1.014039
4,-1.643606,-0.149442,-2.247792,-1.0,-0.207909,-0.314407,-0.667138,-0.001282,-0.201168,-0.913400,0.999665,-0.062121,1.277124,-0.938121,1.037504,0.405173,1.001339,-0.996771,-0.047869,-0.450262,-0.269934,-0.151039,0.373350,-0.179202,-0.010561,-0.615378,-0.136067,-0.615378,-0.587868,2.16641,-0.23598,-0.999888,1.014039

In [716]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(df_include, df['covered'], test_size=0.2)